name: main
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-release:
    name: Build project and create release
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get project details
        id: meta
        run: echo "tag=$(git tag --points-at ${{ github.sha }})" | tee -a $GITHUB_OUTPUT
      - name: Set up Java
        if: ${{ steps.meta.outputs.tag != '' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Set up Gradle
        if: ${{ steps.meta.outputs.tag != '' }}
        uses: gradle/actions/setup-gradle@v4
      - name: Build project
        if: ${{ steps.meta.outputs.tag != '' }}
        run: ./gradlew build
      - name: Create release
        if: ${{ steps.meta.outputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/build/libs/*
          tag_name: ${{ steps.meta.outputs.tag }}
